FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache git curl bash

RUN npm install -g expo-cli @expo/ngrok

COPY package.json ./
RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 8082 19000 19001 19002

CMD ["npx", "expo", "start", "--tunnel"]
