--
-- PostgreSQL database dump
--

\restrict 6nFQDSsCkjBQ0Nx1kbYL3QGNgtJ9aj7gGb49jaABRBjbdQTjC3F1udPJ69Eglsp

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 17.9 (Ubuntu 17.9-0ubuntu0.25.10.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: blocks; Type: TABLE; Schema: public; Owner: instagram_user
--

CREATE TABLE public.blocks (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    blocked_id bigint NOT NULL,
    blocker_id bigint NOT NULL
);


ALTER TABLE public.blocks OWNER TO instagram_user;

--
-- Name: blocks_id_seq; Type: SEQUENCE; Schema: public; Owner: instagram_user
--

ALTER TABLE public.blocks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blocks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: instagram_user
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    text character varying(1000) NOT NULL,
    parent_comment_id bigint,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.comments OWNER TO instagram_user;

--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: instagram_user
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: follows; Type: TABLE; Schema: public; Owner: instagram_user
--

CREATE TABLE public.follows (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    follower_id bigint NOT NULL,
    following_id bigint NOT NULL
);


ALTER TABLE public.follows OWNER TO instagram_user;

--
-- Name: follows_id_seq; Type: SEQUENCE; Schema: public; Owner: instagram_user
--

ALTER TABLE public.follows ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.follows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: likes; Type: TABLE; Schema: public; Owner: instagram_user
--

CREATE TABLE public.likes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    comment_id bigint,
    message_id bigint,
    post_id bigint,
    user_id bigint NOT NULL
);


ALTER TABLE public.likes OWNER TO instagram_user;

--
-- Name: likes_id_seq; Type: SEQUENCE; Schema: public; Owner: instagram_user
--

ALTER TABLE public.likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: instagram_user
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    content character varying(2000) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_read boolean,
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    shared_comment_id bigint,
    shared_post_id bigint
);


ALTER TABLE public.messages OWNER TO instagram_user;

--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: instagram_user
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: instagram_user
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_read boolean,
    message character varying(255),
    reference_id bigint,
    type character varying(255) NOT NULL,
    actor_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['LIKE_POST'::character varying, 'LIKE_COMMENT'::character varying, 'LIKE_MESSAGE'::character varying, 'COMMENT'::character varying, 'COMMENT_REPLY'::character varying, 'FOLLOW'::character varying, 'MENTION'::character varying, 'STORY_VIEW'::character varying, 'MESSAGE'::character varying, 'SHARED_POST'::character varying, 'SHARED_COMMENT'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO instagram_user;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: instagram_user
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: posts; Type: TABLE; Schema: public; Owner: instagram_user
--

CREATE TABLE public.posts (
    id bigint NOT NULL,
    caption character varying(22000),
    created_at timestamp(6) without time zone NOT NULL,
    media_url character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.posts OWNER TO instagram_user;

--
-- Name: posts_id_seq; Type: SEQUENCE; Schema: public; Owner: instagram_user
--

ALTER TABLE public.posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saved_posts; Type: TABLE; Schema: public; Owner: instagram_user
--

CREATE TABLE public.saved_posts (
    id bigint NOT NULL,
    saved_at timestamp(6) without time zone NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.saved_posts OWNER TO instagram_user;

--
-- Name: saved_posts_id_seq; Type: SEQUENCE; Schema: public; Owner: instagram_user
--

ALTER TABLE public.saved_posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saved_posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stories; Type: TABLE; Schema: public; Owner: instagram_user
--

CREATE TABLE public.stories (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expiration_time timestamp(6) without time zone NOT NULL,
    media_url character varying(255) NOT NULL,
    recipient_id bigint,
    shared_post_id bigint,
    user_id bigint NOT NULL
);


ALTER TABLE public.stories OWNER TO instagram_user;

--
-- Name: stories_id_seq; Type: SEQUENCE; Schema: public; Owner: instagram_user
--

ALTER TABLE public.stories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: story_views; Type: TABLE; Schema: public; Owner: instagram_user
--

CREATE TABLE public.story_views (
    id bigint NOT NULL,
    viewed_at timestamp(6) without time zone NOT NULL,
    story_id bigint NOT NULL,
    viewer_id bigint NOT NULL
);


ALTER TABLE public.story_views OWNER TO instagram_user;

--
-- Name: story_views_id_seq; Type: SEQUENCE; Schema: public; Owner: instagram_user
--

ALTER TABLE public.story_views ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.story_views_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: instagram_user
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    bio character varying(300),
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(100) NOT NULL,
    is_active boolean,
    password character varying(255) NOT NULL,
    profile_picture character varying(255),
    username character varying(50) NOT NULL
);


ALTER TABLE public.users OWNER TO instagram_user;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: instagram_user
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: blocks; Type: TABLE DATA; Schema: public; Owner: instagram_user
--

COPY public.blocks (id, created_at, blocked_id, blocker_id) FROM stdin;
\.


--
-- Data for Name: comments; Type: TABLE DATA; Schema: public; Owner: instagram_user
--

COPY public.comments (id, created_at, text, parent_comment_id, post_id, user_id) FROM stdin;
\.


--
-- Data for Name: follows; Type: TABLE DATA; Schema: public; Owner: instagram_user
--

COPY public.follows (id, created_at, follower_id, following_id) FROM stdin;
\.


--
-- Data for Name: likes; Type: TABLE DATA; Schema: public; Owner: instagram_user
--

COPY public.likes (id, created_at, comment_id, message_id, post_id, user_id) FROM stdin;
\.


--
-- Data for Name: messages; Type: TABLE DATA; Schema: public; Owner: instagram_user
--

COPY public.messages (id, content, created_at, is_read, receiver_id, sender_id, shared_comment_id, shared_post_id) FROM stdin;
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: instagram_user
--

COPY public.notifications (id, created_at, is_read, message, reference_id, type, actor_id, user_id) FROM stdin;
\.


--
-- Data for Name: posts; Type: TABLE DATA; Schema: public; Owner: instagram_user
--

COPY public.posts (id, caption, created_at, media_url, user_id) FROM stdin;
\.


--
-- Data for Name: saved_posts; Type: TABLE DATA; Schema: public; Owner: instagram_user
--

COPY public.saved_posts (id, saved_at, post_id, user_id) FROM stdin;
\.


--
-- Data for Name: stories; Type: TABLE DATA; Schema: public; Owner: instagram_user
--

COPY public.stories (id, created_at, expiration_time, media_url, recipient_id, shared_post_id, user_id) FROM stdin;
\.


--
-- Data for Name: story_views; Type: TABLE DATA; Schema: public; Owner: instagram_user
--

COPY public.story_views (id, viewed_at, story_id, viewer_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: instagram_user
--

COPY public.users (id, bio, created_at, email, is_active, password, profile_picture, username) FROM stdin;
1	\N	2026-05-05 23:01:16.328444	anass@gmail.com	t	$2a$10$1GcXxZixUrfRea3d2L.kBeQ4R8dfKeKP5EQDV.exJC5qMHlX4WPOC	\N	anass
2	\N	2026-05-05 23:02:35.443991	anassigh@gmail.com	t	$2a$10$5NgDsOBMtE0oEcle6CuWA.yLZFeUI8ouE9cfhit.xqNxEcWDl2I4a	\N	anassigh
3	\N	2026-05-05 23:56:14.990373	ayoub@gmail.com	t	$2a$10$YwCJ/F8KH2k2CBdFxwRcgeZdZ7/sSSqha6YRjS3PSJ5IwubEtyY9W	\N	ayoub
4	\N	2026-05-06 15:23:57.729389	najla@gmail.com	t	$2a$10$KpqWoOhIfAf2BCkQKVtiQONgiviAUc0eUr5YPQ3B7798nhrHOE/cu	\N	najla
5	\N	2026-05-06 15:29:15.022322	bouchra@gmail.com	t	$2a$10$eU2alx.UMsMFnpLXgqyPQuKXnAToH5c5mNxEWPKnMZxyaofU9dgGW	\N	bouchra
\.


--
-- Name: blocks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instagram_user
--

SELECT pg_catalog.setval('public.blocks_id_seq', 1, false);


--
-- Name: comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instagram_user
--

SELECT pg_catalog.setval('public.comments_id_seq', 1, false);


--
-- Name: follows_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instagram_user
--

SELECT pg_catalog.setval('public.follows_id_seq', 1, false);


--
-- Name: likes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instagram_user
--

SELECT pg_catalog.setval('public.likes_id_seq', 1, false);


--
-- Name: messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instagram_user
--

SELECT pg_catalog.setval('public.messages_id_seq', 1, false);


--
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instagram_user
--

SELECT pg_catalog.setval('public.notifications_id_seq', 1, false);


--
-- Name: posts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instagram_user
--

SELECT pg_catalog.setval('public.posts_id_seq', 1, false);


--
-- Name: saved_posts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instagram_user
--

SELECT pg_catalog.setval('public.saved_posts_id_seq', 1, false);


--
-- Name: stories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instagram_user
--

SELECT pg_catalog.setval('public.stories_id_seq', 1, false);


--
-- Name: story_views_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instagram_user
--

SELECT pg_catalog.setval('public.story_views_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instagram_user
--

SELECT pg_catalog.setval('public.users_id_seq', 5, true);


--
-- Name: blocks blocks_pkey; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT blocks_pkey PRIMARY KEY (id);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: follows follows_pkey; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.follows
    ADD CONSTRAINT follows_pkey PRIMARY KEY (id);


--
-- Name: likes likes_pkey; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT likes_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);


--
-- Name: saved_posts saved_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.saved_posts
    ADD CONSTRAINT saved_posts_pkey PRIMARY KEY (id);


--
-- Name: stories stories_pkey; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.stories
    ADD CONSTRAINT stories_pkey PRIMARY KEY (id);


--
-- Name: story_views story_views_pkey; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.story_views
    ADD CONSTRAINT story_views_pkey PRIMARY KEY (id);


--
-- Name: likes uk2jovqhqo324cubdomovkex03b; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT uk2jovqhqo324cubdomovkex03b UNIQUE (user_id, post_id);


--
-- Name: follows uk4faelgsm2rxl2jf3iyjy981ro; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.follows
    ADD CONSTRAINT uk4faelgsm2rxl2jf3iyjy981ro UNIQUE (follower_id, following_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: blocks uko6p3yjxo8qvcqrxt673wxsx63; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT uko6p3yjxo8qvcqrxt673wxsx63 UNIQUE (blocker_id, blocked_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: saved_posts ukrp4caf9aruyad4113wv29bowp; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.saved_posts
    ADD CONSTRAINT ukrp4caf9aruyad4113wv29bowp UNIQUE (user_id, post_id);


--
-- Name: likes uksg7vao6v9l46c3nj31fbu4wu6; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT uksg7vao6v9l46c3nj31fbu4wu6 UNIQUE (user_id, comment_id);


--
-- Name: story_views uktja66va44twpgggklwb9vmp5w; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.story_views
    ADD CONSTRAINT uktja66va44twpgggklwb9vmp5w UNIQUE (story_id, viewer_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: story_views fk2y4acyhro3w5xrmku47osiry9; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.story_views
    ADD CONSTRAINT fk2y4acyhro3w5xrmku47osiry9 FOREIGN KEY (viewer_id) REFERENCES public.users(id);


--
-- Name: notifications fk4sd9fik0uthbk6d9rsxco4uja; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk4sd9fik0uthbk6d9rsxco4uja FOREIGN KEY (actor_id) REFERENCES public.users(id);


--
-- Name: messages fk4ui4nnwntodh6wjvck53dbk9m; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk4ui4nnwntodh6wjvck53dbk9m FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: posts fk5lidm6cqbc7u4xhqpxm898qme; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fk5lidm6cqbc7u4xhqpxm898qme FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: stories fk6myglpklwrt8sswsdjxqc7trj; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.stories
    ADD CONSTRAINT fk6myglpklwrt8sswsdjxqc7trj FOREIGN KEY (shared_post_id) REFERENCES public.posts(id);


--
-- Name: comments fk7h839m3lkvhbyv3bcdv7sm4fj; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk7h839m3lkvhbyv3bcdv7sm4fj FOREIGN KEY (parent_comment_id) REFERENCES public.comments(id);


--
-- Name: messages fk7ti6q9qdayk332q340220a9r0; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk7ti6q9qdayk332q340220a9r0 FOREIGN KEY (shared_post_id) REFERENCES public.posts(id);


--
-- Name: comments fk8omq0tc18jd43bu5tjh6jvraq; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: saved_posts fk9poxgdc1595vxdxkyg202x4ge; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.saved_posts
    ADD CONSTRAINT fk9poxgdc1595vxdxkyg202x4ge FOREIGN KEY (post_id) REFERENCES public.posts(id);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: messages fkcldu14f1kucj8wlt88ig0vjfr; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fkcldu14f1kucj8wlt88ig0vjfr FOREIGN KEY (shared_comment_id) REFERENCES public.comments(id);


--
-- Name: likes fke4guax66lb963pf27kvm7ikik; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT fke4guax66lb963pf27kvm7ikik FOREIGN KEY (comment_id) REFERENCES public.comments(id);


--
-- Name: comments fkh4c7lvsc298whoyd4w9ta25cr; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkh4c7lvsc298whoyd4w9ta25cr FOREIGN KEY (post_id) REFERENCES public.posts(id);


--
-- Name: blocks fkjcracc6rem4ddb6gtkaxhfsvu; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT fkjcracc6rem4ddb6gtkaxhfsvu FOREIGN KEY (blocked_id) REFERENCES public.users(id);


--
-- Name: blocks fkl05bxnwmimx5n5tsgrgnguvu6; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT fkl05bxnwmimx5n5tsgrgnguvu6 FOREIGN KEY (blocker_id) REFERENCES public.users(id);


--
-- Name: story_views fknpayqngtq4lo8dgqqpo01vcrv; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.story_views
    ADD CONSTRAINT fknpayqngtq4lo8dgqqpo01vcrv FOREIGN KEY (story_id) REFERENCES public.stories(id);


--
-- Name: likes fknvx9seeqqyy71bij291pwiwrg; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT fknvx9seeqqyy71bij291pwiwrg FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: follows fkonkdkae2ngtx70jqhsh7ol6uq; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.follows
    ADD CONSTRAINT fkonkdkae2ngtx70jqhsh7ol6uq FOREIGN KEY (following_id) REFERENCES public.users(id);


--
-- Name: follows fkqnkw0cwwh6572nyhvdjqlr163; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.follows
    ADD CONSTRAINT fkqnkw0cwwh6572nyhvdjqlr163 FOREIGN KEY (follower_id) REFERENCES public.users(id);


--
-- Name: likes fkrsvs4iro2qcipio37ysd4isdj; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT fkrsvs4iro2qcipio37ysd4isdj FOREIGN KEY (message_id) REFERENCES public.messages(id);


--
-- Name: likes fkry8tnr4x2vwemv2bb0h5hyl0x; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT fkry8tnr4x2vwemv2bb0h5hyl0x FOREIGN KEY (post_id) REFERENCES public.posts(id);


--
-- Name: saved_posts fks9a5ulcshnympbu557ps3qdlv; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.saved_posts
    ADD CONSTRAINT fks9a5ulcshnympbu557ps3qdlv FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: stories fkshv2ytgbsn9w9mpu43mc6ln6j; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.stories
    ADD CONSTRAINT fkshv2ytgbsn9w9mpu43mc6ln6j FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: messages fkt05r0b6n0iis8u7dfna4xdh73; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fkt05r0b6n0iis8u7dfna4xdh73 FOREIGN KEY (receiver_id) REFERENCES public.users(id);


--
-- Name: stories fkto6bnbk0ekp4u6cxq8e1r4jrm; Type: FK CONSTRAINT; Schema: public; Owner: instagram_user
--

ALTER TABLE ONLY public.stories
    ADD CONSTRAINT fkto6bnbk0ekp4u6cxq8e1r4jrm FOREIGN KEY (recipient_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 6nFQDSsCkjBQ0Nx1kbYL3QGNgtJ9aj7gGb49jaABRBjbdQTjC3F1udPJ69Eglsp

